### ISSUE TITLE
RuntimeError: CUDA call failed (correlation_forward_cuda at correlation_cuda.cc:82)

### ISSUE THREAD

**Issue by vua** [Kinpzz/RCRNet-Pytorch#2]
RuntimeError: CUDA call failed (correlation_forward_cuda at correlation_cuda.cc:82) 
 According to the readme.md, we changed the same configuration. When we run generate_pseudo_labels.py, the program appears above error, could you please help us to solve this problem?

**Comment by Kinpzz** [comment]
@vua Thanks for your interest. And I am glad to help you. 
Have you successfully installed the flownet2.0? 
Please provide more information including the log output and your environment setup. Thanks.

**Comment by vua** [comment]
Running on GeForce GTX 1080
Loading state dict from: models/pseudo_label_generator_5.pth
06 16:20:33 Load model, Time usage:
	IO: 1.5645217895507812, initialize parameters: 0.2070169448852539
Generating pseudo-labels at data/pseudo-labels
label interval: 5
frame between label num: 1
  0%|                                                   | 0/403 [00:00<?, ?it/s]error in correlation_forward_cuda_kernel: CUDA driver version is insufficient for CUDA runtime version

Traceback (most recent call last):
  File "generate_pseudo_labels.py", line 142, in <module>
    generate_pseudo_label()
  File "generate_pseudo_labels.py", line 120, in generate_pseudo_label
    pseudo_label = pseudo_label_generator.generate_pseudo_label(images[i], images[0], images[-1], labels[0], labels[-1])
  File "/home/deeplearning/桌面/ljw/RCRNet-Pytorch-master/libs/networks/pseudo_label_generator.py", line 70, in generate_pseudo_label
    flow_forward = compute_flow(self.flownet, frame, frame_l)#l到k的光流 Olk
  File "/home/deeplearning/桌面/ljw/RCRNet-Pytorch-master/libs/networks/pseudo_label_generator.py", line 34, in compute_flow
    return flownet(im)
  File "/home/deeplearning/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/deeplearning/桌面/ljw/RCRNet-Pytorch-master/flownet2/models.py", line 118, in forward
    flownetc_flow2 = self.flownetc(x)[0]
  File "/home/deeplearning/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "flownet2/networks/FlowNetC.py", line 86, in forward
    out_corr = self.corr(out_conv3a, out_conv3b) # False
  File "/home/deeplearning/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "flownet2/networks/correlation_package/correlation.py", line 59, in forward
    result = CorrelationFunction(self.pad_size, self.kernel_size, self.max_displacement,self.stride1, self.stride2, self.corr_multiply)(input1, input2)
  File "flownet2/networks/correlation_package/correlation.py", line 27, in forward
    self.pad_size, self.kernel_size, self.max_displacement,self.stride1, self.stride2, self.corr_multiply)
RuntimeError: CUDA call failed (correlation_forward_cuda at correlation_cuda.cc:82)
frame #0: <unknown function> + 0x14a30 (0x7fbf7c98da30 in /home/deeplearning/anaconda3/lib/python3.5/site-packages/correlation_cuda-0.0.0-py3.5-linux-x86_64.egg/correlation_cuda.cpython-35m-x86_64-linux-gnu.so)
frame #1: <unknown function> + 0x11668 (0x7fbf7c98a668 in /home/deeplearning/anaconda3/lib/python3.5/site-packages/correlation_cuda-0.0.0-py3.5-linux-x86_64.egg/correlation_cuda.cpython-35m-x86_64-linux-gnu.so)
<omitting python frames>
frame #10: THPFunction_do_forward(THPFunction*, _object*) + 0x2ad (0x7fbfaafdbfbd in /home/deeplearning/anaconda3/lib/python3.5/site-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so)
frame #62: __libc_start_main + 0xe7 (0x7fbfc6bf4b97 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by vua** [comment]
python3.5,cuda9.0,pytorch0.4.1,nvidia-driver390,

**Comment by Kinpzz** [comment]
As the log suggests ``CUDA driver version is insufficient for CUDA runtime version``, I believe this is due to the driver of your GPU. Please try to update the nvidia-driver or search for more solutions on the Internet.

**Comment by vua** [comment]
Thank you very much. We have solved the problem.

**Comment by Wangle-maker** [comment]
> 非常感谢。我们已经解决了这个问题。

您是怎么解决的呢
